CREATE TABLE IF NOT EXISTS "im_private_message" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY COMMENT '编号',
    "client_message_id" varchar(64) DEFAULT NULL COMMENT '客户端消息编号',
    "sender_id" bigint NOT NULL COMMENT '发送人编号',
    "sender_type" tinyint NOT NULL DEFAULT 1 COMMENT '发送方类型: 1=用户 2=机器人 3=人工客服',
    "receiver_id" bigint NOT NULL COMMENT '接收人编号',
    "receiver_type" tinyint NOT NULL DEFAULT 1 COMMENT '接收方类型: 1=用户 2=机器人 3=人工客服',
    "type" smallint NOT NULL COMMENT '消息类型',
    "content" varchar(8192) DEFAULT NULL COMMENT '消息内容',
    "status" tinyint NOT NULL COMMENT '消息状态',
    "send_time" timestamp NOT NULL COMMENT '发送时间',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id"),
    CONSTRAINT "uk_im_private_message_sender_client" UNIQUE ("sender_type", "sender_id", "client_message_id", "tenant_id")
) COMMENT 'IM 私聊消息表';

CREATE TABLE IF NOT EXISTS "im_group_message" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY COMMENT '编号',
    "client_message_id" varchar(64) DEFAULT NULL COMMENT '客户端消息编号',
    "sender_id" bigint NOT NULL COMMENT '发送人编号',
    "group_id" bigint NOT NULL COMMENT '群编号',
    "type" smallint NOT NULL COMMENT '消息类型',
    "content" varchar(8192) DEFAULT NULL COMMENT '消息内容',
    "status" tinyint NOT NULL COMMENT '消息状态',
    "send_time" timestamp NOT NULL COMMENT '发送时间',
    "receiver_user_ids" varchar(1024) DEFAULT NULL COMMENT '定向接收用户编号列表',
    "at_user_ids" varchar(1024) DEFAULT NULL COMMENT '@ 目标用户编号列表',
    "receipt_status" tinyint NOT NULL DEFAULT 0 COMMENT '回执状态',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id"),
    CONSTRAINT "uk_im_group_message_sender_client" UNIQUE ("sender_id", "client_message_id", "tenant_id")
) COMMENT 'IM 群聊消息表';

CREATE TABLE IF NOT EXISTS "im_group" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY COMMENT '编号',
    "name" varchar(64) NOT NULL COMMENT '群名称',
    "owner_user_id" bigint NOT NULL COMMENT '群主用户编号',
    "avatar" varchar(512) DEFAULT NULL COMMENT '群头像',
    "notice" varchar(2048) DEFAULT NULL COMMENT '群公告',
    "banned" bit DEFAULT FALSE COMMENT '是否封禁',
    "banned_reason" varchar(512) DEFAULT NULL COMMENT '封禁原因',
    "banned_time" timestamp DEFAULT NULL COMMENT '封禁时间',
    "status" tinyint NOT NULL COMMENT '群状态',
    "dissolved_time" timestamp DEFAULT NULL COMMENT '解散时间',
    "muted_all" bit DEFAULT FALSE COMMENT '是否全群禁言',
    "join_approval" bit NOT NULL DEFAULT FALSE COMMENT '进群是否需群主 / 管理员审批；false 自由进群，true 需审批',
    "pinned_message_ids" varchar(128) DEFAULT NULL COMMENT '群置顶消息编号列表，逗号分隔',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT 'IM 群信息表';

CREATE TABLE IF NOT EXISTS "im_group_member" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY COMMENT '编号',
    "group_id" bigint NOT NULL COMMENT '群编号',
    "user_id" bigint NOT NULL COMMENT '用户编号',
    "display_user_name" varchar(64) DEFAULT NULL COMMENT '组内显示名',
    "group_remark" varchar(64) DEFAULT NULL COMMENT '群备注',
    "silent" bit DEFAULT FALSE COMMENT '是否免打扰',
    "status" tinyint NOT NULL COMMENT '成员状态',
    "role" tinyint NOT NULL DEFAULT 3 COMMENT '成员角色：1=群主 2=管理员 3=普通成员',
    "join_time" timestamp DEFAULT NULL COMMENT '入群时间',
    "add_source" tinyint DEFAULT NULL COMMENT '加入来源',
    "inviter_user_id" bigint DEFAULT NULL COMMENT '邀请人用户编号；用户主动申请进群时为 NULL',
    "quit_time" timestamp DEFAULT NULL COMMENT '退群时间',
    "mute_end_time" timestamp DEFAULT NULL COMMENT '禁言到期时间',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id"),
    CONSTRAINT "uk_im_group_member" UNIQUE ("group_id", "user_id", "tenant_id")
) COMMENT 'IM 群成员表';

CREATE TABLE IF NOT EXISTS "im_friend" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY COMMENT '编号',
    "user_id" bigint NOT NULL COMMENT '用户编号',
    "friend_user_id" bigint NOT NULL COMMENT '好友用户编号',
    "silent" bit DEFAULT FALSE COMMENT '是否免打扰',
    "display_name" varchar(64) NOT NULL DEFAULT '' COMMENT '好友展示备注（仅自己可见）',
    "add_source" tinyint DEFAULT NULL COMMENT '添加来源',
    "pinned" bit DEFAULT FALSE COMMENT '是否置顶联系人',
    "blocked" bit DEFAULT FALSE COMMENT '是否拉黑',
    "status" tinyint NOT NULL COMMENT '好友状态',
    "add_time" timestamp DEFAULT NULL COMMENT '添加好友时间',
    "delete_time" timestamp DEFAULT NULL COMMENT '删除好友时间',
    "phone" varchar(255) NOT NULL DEFAULT '' COMMENT '备注电话（多号逗号分隔，仅自己可见）',
    "remark" varchar(500) NOT NULL DEFAULT '' COMMENT '文字备注（仅自己可见）',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id"),
    CONSTRAINT "uk_user_friend" UNIQUE ("user_id", "friend_user_id", "tenant_id")
) COMMENT 'IM 好友关系表';

CREATE TABLE IF NOT EXISTS "im_friend_request" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY COMMENT '编号',
    "from_user_id" bigint NOT NULL COMMENT '发起方用户编号',
    "to_user_id" bigint NOT NULL COMMENT '接收方用户编号',
    "handle_result" tinyint NOT NULL DEFAULT 0 COMMENT '处理结果；0未处理；1同意；2拒绝',
    "apply_content" varchar(255) DEFAULT NULL COMMENT '申请理由',
    "handle_content" varchar(255) DEFAULT NULL COMMENT '处理理由',
    "display_name" varchar(64) DEFAULT NULL COMMENT '发起方对接收方的备注',
    "add_source" tinyint DEFAULT NULL COMMENT '添加来源',
    "handle_time" timestamp DEFAULT NULL COMMENT '处理时间',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id"),
    CONSTRAINT "uk_im_friend_request" UNIQUE ("from_user_id", "to_user_id", "tenant_id")
) COMMENT 'IM 好友申请记录表';

CREATE TABLE IF NOT EXISTS "im_group_request" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY COMMENT '编号',
    "group_id" bigint NOT NULL COMMENT '群编号',
    "user_id" bigint NOT NULL COMMENT '申请人 / 被邀请人用户编号',
    "inviter_user_id" bigint DEFAULT NULL COMMENT '邀请人用户编号；NULL=主动申请；非NULL=被邀请待审批',
    "apply_content" varchar(255) DEFAULT NULL COMMENT '申请理由',
    "add_source" tinyint DEFAULT NULL COMMENT '加入来源',
    "handle_result" tinyint NOT NULL DEFAULT 0 COMMENT '处理结果；0未处理；1同意；2拒绝',
    "handle_user_id" bigint DEFAULT NULL COMMENT '处理人用户编号',
    "handle_content" varchar(255) DEFAULT NULL COMMENT '处理理由',
    "handle_time" timestamp DEFAULT NULL COMMENT '处理时间',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id"),
    CONSTRAINT "uk_im_group_request" UNIQUE ("group_id", "user_id", "tenant_id")
) COMMENT 'IM 加群申请记录表';

CREATE TABLE IF NOT EXISTS "im_face_pack" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY COMMENT '编号',
    "name" varchar(64) NOT NULL COMMENT '表情包名称',
    "icon" varchar(512) DEFAULT NULL COMMENT '表情包图标（面板底部 tab 显示）',
    "sort" int NOT NULL DEFAULT 0 COMMENT '排序',
    "status" tinyint NOT NULL COMMENT '状态',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT 'IM 表情包表';

CREATE TABLE IF NOT EXISTS "im_face_pack_item" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY COMMENT '编号',
    "pack_id" bigint NOT NULL COMMENT '所属表情包编号',
    "url" varchar(512) NOT NULL COMMENT '表情图 URL',
    "name" varchar(64) DEFAULT NULL COMMENT '表情名（可选；如「狗头」「捂脸」）',
    "width" int NOT NULL DEFAULT 0 COMMENT '渲染宽度（像素）',
    "height" int NOT NULL DEFAULT 0 COMMENT '渲染高度（像素）',
    "sort" int NOT NULL DEFAULT 0 COMMENT '排序',
    "status" tinyint NOT NULL COMMENT '状态',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT 'IM 表情包项表';

CREATE TABLE IF NOT EXISTS "im_rtc_call" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY COMMENT '编号',
    "room" varchar(64) NOT NULL COMMENT '业务通话编号',
    "conversation_type" tinyint NOT NULL COMMENT '会话类型',
    "media_type" tinyint NOT NULL COMMENT '媒体类型',
    "inviter_user_id" bigint NOT NULL COMMENT '发起人用户编号',
    "group_id" bigint DEFAULT NULL COMMENT '群编号',
    "status" tinyint NOT NULL COMMENT '通话状态',
    "end_reason" tinyint DEFAULT NULL COMMENT '结束原因',
    "start_time" timestamp NOT NULL COMMENT '发起时间',
    "accept_time" timestamp DEFAULT NULL COMMENT '接通时间',
    "end_time" timestamp DEFAULT NULL COMMENT '结束时间',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT 'IM 通话记录表';

CREATE TABLE IF NOT EXISTS "im_rtc_participant" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY COMMENT '编号',
    "call_id" bigint NOT NULL COMMENT '通话编号',
    "room" varchar(64) NOT NULL COMMENT '业务通话编号',
    "user_id" bigint NOT NULL COMMENT '参与者用户编号',
    "role" tinyint NOT NULL COMMENT '参与角色',
    "status" tinyint NOT NULL COMMENT '参与状态',
    "invite_time" timestamp NOT NULL COMMENT '被邀请时间',
    "accept_time" timestamp DEFAULT NULL COMMENT '接听时间',
    "leave_time" timestamp DEFAULT NULL COMMENT '离开时间',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id"),
    CONSTRAINT "uk_im_rtc_participant_room_user" UNIQUE ("room", "user_id", "tenant_id")
) COMMENT 'IM 通话参与者表';

CREATE TABLE IF NOT EXISTS "im_face_user_item" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY COMMENT '编号',
    "user_id" bigint NOT NULL COMMENT '所属用户编号',
    "url" varchar(512) NOT NULL COMMENT '表情图 URL',
    "name" varchar(64) DEFAULT NULL COMMENT '表情名（可选）',
    "width" int NOT NULL DEFAULT 0 COMMENT '渲染宽度（像素）',
    "height" int NOT NULL DEFAULT 0 COMMENT '渲染高度（像素）',
    "sort" int NOT NULL DEFAULT 0 COMMENT '排序',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id"),
    CONSTRAINT "uk_im_face_user_item_user_url_deleted" UNIQUE ("user_id", "url", "deleted")
) COMMENT 'IM 用户私有表情表';

CREATE TABLE IF NOT EXISTS "im_channel" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY COMMENT '编号',
    "code" varchar(64) NOT NULL COMMENT '频道业务码；唯一',
    "name" varchar(64) NOT NULL COMMENT '频道名称',
    "avatar" varchar(512) DEFAULT NULL COMMENT '频道头像',
    "sort" int NOT NULL DEFAULT 0 COMMENT '排序',
    "status" tinyint NOT NULL DEFAULT 0 COMMENT '状态；0 启用 1 停用',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT 'IM 频道表';

CREATE TABLE IF NOT EXISTS "im_channel_material" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY COMMENT '编号',
    "channel_id" bigint NOT NULL COMMENT '频道编号',
    "type" tinyint NOT NULL COMMENT '内容类型；1 站内富文本 2 外链',
    "title" varchar(128) NOT NULL COMMENT '标题',
    "cover_url" varchar(512) DEFAULT NULL COMMENT '封面图',
    "summary" varchar(255) DEFAULT NULL COMMENT '摘要',
    "content" clob DEFAULT NULL COMMENT '正文；富文本 HTML',
    "url" varchar(512) DEFAULT NULL COMMENT '跳转链接；为空时点击在客户端内置详情页拉 content；非空则跳 url',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT 'IM 频道素材表';

CREATE TABLE IF NOT EXISTS "im_channel_message" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY COMMENT '编号',
    "channel_id" bigint NOT NULL COMMENT '频道编号；冗余 im_channel_material.channel_id 便于检索',
    "material_id" bigint NOT NULL COMMENT '关联素材编号',
    "type" smallint NOT NULL COMMENT '消息类型',
    "content" varchar(8192) DEFAULT NULL COMMENT '消息内容；推送时 payload JSON 快照；不含富文本正文',
    "receiver_user_ids" varchar(1024) DEFAULT NULL COMMENT '接收人编号列表；逗号分隔；为空表示全员',
    "send_time" timestamp NOT NULL COMMENT '发送时间',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT 'IM 频道消息表';

CREATE TABLE IF NOT EXISTS "im_sensitive_word" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY COMMENT '编号',
    "word" varchar(128) NOT NULL COMMENT '敏感词',
    "status" tinyint NOT NULL DEFAULT 0 COMMENT '状态；0 启用 1 停用',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id"),
    CONSTRAINT "uk_im_sensitive_word" UNIQUE ("word", "tenant_id")
) COMMENT 'IM 敏感词表';

CREATE TABLE IF NOT EXISTS "im_users" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "username" varchar(30) NOT NULL DEFAULT '',
    "password" varchar(100) NOT NULL DEFAULT '',
    "nickname" varchar(30) NOT NULL DEFAULT '',
    "remark" varchar(500) DEFAULT NULL,
    "email" varchar(50) DEFAULT '',
    "mobile" varchar(11) DEFAULT '',
    "sex" tinyint DEFAULT 0,
    "avatar" varchar(100) DEFAULT '',
    "avatar_thumb" varchar(512) DEFAULT '',
    "signature" varchar(255) DEFAULT '',
    "status" tinyint NOT NULL DEFAULT 0,
    "is_banned" bit NOT NULL DEFAULT FALSE,
    "ban_reason" varchar(255) DEFAULT NULL,
    "login_ip" varchar(50) DEFAULT '',
    "login_date" timestamp DEFAULT NULL,
    "device_type" tinyint DEFAULT NULL COMMENT '设备类型（最近活跃终端）；枚举 TerminalEnum',
    "register_time" timestamp DEFAULT NULL,
    "allow_find_by_mobile" bit NOT NULL DEFAULT TRUE COMMENT '是否允许通过手机号找到我（隐私设置）',
    "allow_find_by_username" bit NOT NULL DEFAULT TRUE COMMENT '是否允许通过账号找到我（隐私设置）',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT 'IM 用户信息表';

-- ==================== 迁移脚本（已有数据库执行）====================
-- 如 im_users 表尚未包含以下字段，请手动执行：
--  ALTER TABLE `im_users` ADD COLUMN `allow_find_by_mobile` bit NOT NULL DEFAULT TRUE;
-- ALTER TABLE `im_users` ADD COLUMN `allow_find_by_username` bit NOT NULL DEFAULT TRUE;
-- ALTER TABLE `im_users` ADD COLUMN `device_type` tinyint DEFAULT NULL COMMENT '设备类型（最近活跃终端）；枚举 TerminalEnum';

-- ==================== 红包 ====================
CREATE TABLE IF NOT EXISTS "im_red_packet" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY COMMENT '编号',
    "no" varchar(64) NOT NULL COMMENT '红包单号',
    "sender_user_id" bigint NOT NULL COMMENT '发送人用户编号',
    "conversation_type" smallint NOT NULL COMMENT '会话类型',
    "receiver_user_id" bigint DEFAULT NULL COMMENT '私聊红包领取人编号',
    "group_id" bigint DEFAULT NULL COMMENT '群编号',
    "type" smallint NOT NULL COMMENT '红包类型',
    "total_amount" int NOT NULL COMMENT '红包总金额，单位：分',
    "total_count" int NOT NULL COMMENT '红包总个数',
    "remain_amount" int NOT NULL COMMENT '剩余金额，单位：分',
    "remain_count" int NOT NULL COMMENT '剩余个数',
    "greeting" varchar(128) DEFAULT NULL COMMENT '祝福语',
    "status" smallint NOT NULL COMMENT '红包状态',
    "expire_time" timestamp DEFAULT NULL COMMENT '过期时间',
    "grabbed_amount" int NOT NULL DEFAULT 0 COMMENT '已领取金额，单位：分',
    "grabbed_count" int NOT NULL DEFAULT 0 COMMENT '已领取个数',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id"),
    CONSTRAINT "uk_im_red_packet_no" UNIQUE ("no", "tenant_id"),
    INDEX "idx_im_red_packet_user_status" ("sender_user_id", "status", "create_time")
) COMMENT 'IM 红包表';

CREATE TABLE IF NOT EXISTS "im_red_packet_grab" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY COMMENT '编号',
    "red_packet_id" bigint NOT NULL COMMENT '红包编号',
    "red_packet_no" varchar(64) NOT NULL COMMENT '红包单号',
    "user_id" bigint NOT NULL COMMENT '领取人用户编号',
    "amount" int NOT NULL COMMENT '领取金额，单位：分',
    "is_best_luck" bit NOT NULL DEFAULT FALSE COMMENT '是否手气最佳',
    "grab_time" timestamp DEFAULT NULL COMMENT '领取时间',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id"),
    CONSTRAINT "uk_im_red_packet_grab" UNIQUE ("red_packet_id", "user_id", "tenant_id")
) COMMENT 'IM 红包领取明细表';

-- ==================== 银行卡 ====================
CREATE TABLE IF NOT EXISTS "im_bank_card" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY COMMENT '编号',
    "user_id" bigint NOT NULL COMMENT '用户编号',
    "card_no_mask" varchar(32) NOT NULL COMMENT '脱敏卡号（仅保留后四位）',
    "bank_name" varchar(64) NOT NULL COMMENT '银行名称',
    "bank_code" varchar(32) NOT NULL COMMENT '银行编码',
    "cardholder" varchar(64) NOT NULL COMMENT '持卡人姓名',
    "id_card_mask" varchar(32) NOT NULL COMMENT '脱敏证件号',
    "phone" varchar(32) DEFAULT NULL COMMENT '银行预留手机号',
    "type" smallint NOT NULL COMMENT '卡片类型',
    "status" smallint NOT NULL COMMENT '状态',
    "is_default" bit NOT NULL DEFAULT FALSE COMMENT '是否默认卡',
    "bind_time" timestamp DEFAULT NULL COMMENT '绑定时间',
    "audit_user_id" bigint DEFAULT NULL COMMENT '审核人编号',
    "audit_time" timestamp DEFAULT NULL COMMENT '审核时间',
    "audit_reason" varchar(255) DEFAULT NULL COMMENT '审核原因',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id"),
    CONSTRAINT "uk_im_bank_card_user" UNIQUE ("user_id", "bank_code", "card_no_mask", "tenant_id")
) COMMENT 'IM 银行卡表';

-- ==================== 转账 ====================
CREATE TABLE IF NOT EXISTS "im_transfer" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY COMMENT '编号',
    "no" varchar(64) NOT NULL COMMENT '转账单号',
    "sender_user_id" bigint NOT NULL COMMENT '转账人用户编号',
    "receiver_user_id" bigint NOT NULL COMMENT '收款人用户编号',
    "amount" int NOT NULL COMMENT '转账金额，单位：分',
    "remark" varchar(255) DEFAULT NULL COMMENT '转账备注',
    "status" smallint NOT NULL COMMENT '转账状态',
    "pay_time" timestamp DEFAULT NULL COMMENT '完成时间',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id"),
    CONSTRAINT "uk_im_transfer_no" UNIQUE ("no", "tenant_id"),
    INDEX "idx_im_transfer_sender" ("sender_user_id", "status", "create_time"),
    INDEX "idx_im_transfer_receiver" ("receiver_user_id", "status", "create_time")
) COMMENT 'IM 转账表';

-- ==================== 提现 ====================
CREATE TABLE IF NOT EXISTS "im_withdraw" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY COMMENT '编号',
    "no" varchar(64) NOT NULL COMMENT '提现单号',
    "user_id" bigint NOT NULL COMMENT '用户编号',
    "bank_card_id" bigint NOT NULL COMMENT '银行卡编号',
    "bank_name" varchar(64) NOT NULL COMMENT '银行名称（快照）',
    "card_no_mask" varchar(32) NOT NULL COMMENT '脱敏卡号（快照）',
    "amount" int NOT NULL COMMENT '提现金额，单位：分',
    "status" smallint NOT NULL COMMENT '提现状态',
    "remark" varchar(255) DEFAULT NULL COMMENT '提现备注',
    "audit_user_id" bigint DEFAULT NULL COMMENT '审核人编号',
    "audit_time" timestamp DEFAULT NULL COMMENT '审核时间',
    "audit_reason" varchar(255) DEFAULT NULL COMMENT '审核原因',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id"),
    CONSTRAINT "uk_im_withdraw_no" UNIQUE ("no", "tenant_id"),
    INDEX "idx_im_withdraw_user" ("user_id", "status", "create_time"),
    INDEX "idx_im_withdraw_bank_card" ("bank_card_id")
) COMMENT 'IM 提现表';

-- ==================== 提现开关配置 ====================
CREATE TABLE IF NOT EXISTS "im_withdraw_config" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY COMMENT '编号',
    "enabled" boolean NOT NULL DEFAULT TRUE COMMENT '是否开放提现',
    "close_message" varchar(512) DEFAULT NULL COMMENT '关闭提现时的用户通知消息',
    "operator_id" bigint DEFAULT NULL COMMENT '最近操作管理员编号',
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT 'IM 提现开关配置表';

-- 默认开启提现
INSERT INTO "im_withdraw_config" ("id", "enabled", "creator", "updater") VALUES (1, TRUE, 'system', 'system');
