-- IM 社交支付 测试表（H2 内存库，风格对齐 create_tables.sql）
-- 仅本阶段（钱包 + 转账）需要的 4 张表；tenant_id / version / 审计字段与框架一致。

CREATE TABLE IF NOT EXISTS "im_user_wallet" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY COMMENT '编号',
    "user_id" bigint NOT NULL COMMENT '用户编号',
    "balance" bigint NOT NULL DEFAULT 0 COMMENT '余额，单位：分',
    "freeze_amount" bigint NOT NULL DEFAULT 0 COMMENT '冻结金额，单位：分',
    "status" tinyint NOT NULL DEFAULT 0 COMMENT '状态：0-正常 1-冻结',
    "version" bigint NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    "creator" varchar(64) DEFAULT '',
    "updater" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id"),
    CONSTRAINT "uk_im_user_wallet_user" UNIQUE ("user_id", "tenant_id")
) COMMENT 'IM 用户钱包';

CREATE TABLE IF NOT EXISTS "im_pay_password" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY COMMENT '编号',
    "user_id" bigint NOT NULL COMMENT '用户编号',
    "password" varchar(100) NOT NULL COMMENT '支付密码 BCrypt 哈希',
    "status" tinyint NOT NULL DEFAULT 0 COMMENT '状态：0-正常 1-已重置',
    "gesture_pattern" varchar(128) DEFAULT NULL COMMENT '手势密码 SHA-256 哈希',
    "gesture_enabled" tinyint NOT NULL DEFAULT 0 COMMENT '手势密码是否开启：0-关闭 1-开启',
    "fingerprint_enabled" tinyint NOT NULL DEFAULT 0 COMMENT '指纹支付是否开启：0-关闭 1-开启',
    "version" bigint NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    "creator" varchar(64) DEFAULT '',
    "updater" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id"),
    CONSTRAINT "uk_im_pay_password_user" UNIQUE ("user_id", "tenant_id")
) COMMENT 'IM 支付密码';

CREATE TABLE IF NOT EXISTS "im_transaction_log" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY COMMENT '编号',
    "tx_no" varchar(64) NOT NULL COMMENT '全局流水号',
    "user_id" bigint NOT NULL COMMENT '用户编号',
    "type" tinyint NOT NULL COMMENT '1-充值 2-转账支出 3-转账收入 4-发红包 5-领红包 6-提现',
    "amount" bigint NOT NULL COMMENT '金额，分；正收入/负支出',
    "balance_after" bigint NOT NULL DEFAULT 0 COMMENT '变动后余额，分',
    "related_user_id" bigint DEFAULT NULL COMMENT '对方用户编号',
    "biz_id" varchar(64) DEFAULT '' COMMENT '关联业务编号',
    "remark" varchar(255) DEFAULT '' COMMENT '备注',
    "version" bigint NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    "creator" varchar(64) DEFAULT '',
    "updater" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id"),
    CONSTRAINT "uk_im_transaction_log_tx" UNIQUE ("tx_no"),
    INDEX "idx_im_transaction_user" ("user_id", "create_time")
) COMMENT 'IM 资金交易流水';

-- ===================== 第 2 阶段（红包 + 银行卡）新增 3 张表 =====================

CREATE TABLE IF NOT EXISTS "im_bank_card" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY COMMENT '编号',
    "user_id" bigint NOT NULL COMMENT '用户编号',
    "card_no" varchar(255) NOT NULL COMMENT '银行卡号（AES 加密存储）',
    "bank_name" varchar(64) DEFAULT '',
    "bank_code" varchar(32) DEFAULT '',
    "card_type" tinyint NOT NULL DEFAULT 1 COMMENT '1-借记卡 2-信用卡',
    "holder_name" varchar(64) DEFAULT '',
    "phone" varchar(32) DEFAULT '',
    "is_default" bit NOT NULL DEFAULT FALSE,
    "status" tinyint NOT NULL DEFAULT 0 COMMENT '0-正常 1-已解绑',
    "version" bigint NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    "creator" varchar(64) DEFAULT '',
    "updater" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id"),
    CONSTRAINT "uk_im_bank_card_user" UNIQUE ("user_id", "card_no")
) COMMENT 'IM 用户银行卡';

CREATE TABLE IF NOT EXISTS "im_red_packet" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY COMMENT '编号',
    "from_user_id" bigint NOT NULL COMMENT '发红包用户编号',
    "total_amount" bigint NOT NULL COMMENT '红包总金额，分',
    "total_count" int NOT NULL COMMENT '红包总个数',
    "type" tinyint NOT NULL DEFAULT 0 COMMENT '0-普通 1-拼手气',
    "transfer_no" varchar(64) NOT NULL COMMENT '红包流水号',
    "status" tinyint NOT NULL DEFAULT 0 COMMENT '0-待领取 1-已抢完 2-已退款 3-已过期',
    "expire_time" timestamp DEFAULT NULL COMMENT '过期时间',
    "remain_amount" bigint NOT NULL DEFAULT 0 COMMENT '剩余金额，分',
    "remain_count" int NOT NULL DEFAULT 0 COMMENT '剩余个数',
    "password" varchar(64) DEFAULT NULL COMMENT '口令红包密码',
    "blessing" varchar(128) DEFAULT '' COMMENT '祝福语',
    "version" bigint NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    "creator" varchar(64) DEFAULT '',
    "updater" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id"),
    CONSTRAINT "uk_im_red_packet_no" UNIQUE ("transfer_no"),
    INDEX "idx_im_red_packet_from" ("from_user_id", "create_time")
) COMMENT 'IM 红包';

